config/routes.rb
BeemUp::Application.routes.draw do

  namespace :admin do
    resources :questions
    resources :zones
    resources :classifieds
    resources :users
    resources :bases
    resources :hotspots
    resources :reports do 
      get :retailers_list, :on => :member
      get :deals_list, :on => :member
    end
  end

  resources :contactus

  resources :archive_contents
  namespace :api do namespace :v1 do
      resources :classified do
        get :get_classifieds, :on => :collection
      end
      resources :users do
        post :sign_up, :action => :create, :on => :collection
        post :update_profile, :action => :update, :on => :collection
        get :delete, :action => :delete_profile, :on => :collection
        get :profile, :on => :collection
        get :token_key, :on => :collection

      end
      resources :questions do
        get :question, :action => :question_of_the_day, :on => :collection
        post :answer, :action => :send_answers, :on => :collection
        
      end
      resources :target_rules
      
      resources :deals do
        get :search, :on => :collection
        get :coupons, :on => :collection
        get :my_coupons, :on => :collection
        get :last_minute_deals, :on => :collection
        get :gifts_or_seasonal_deals, :on => :collection
        get :generate_coupons, :on => :collection
      end
      post '/redeem_coupon/redeem' => 'redeemed_deals#redeem'
      resources :stores do
        get :all , :action => :stores, :on => :collection
      end
      resources :store_categories do
        get :stores, :on => :collection
      end
      resources :categories do
        get :all , :action => :categories, :on => :collection
      end
      resources :user_categories do
        get :categories, :on => :collection
        post :save, :action => :saveUserCategories, :on => :collection

      end
      resources :user_stores do
        get :stores, :on => :collection
        post :save,  :action => :saveUserStores, :on => :collection

      end
      
      resources :wallets do
        get :coupon,  :action => :save_coupon, :on => :collection
        get :mywallet,  :action => :my_wallet, :on => :collection
        get :redeem, :on=> :collection
      end
     
      
    end  end # /api/v1/

  
  resources :temp_images
  resources :temp_users
  resources :credit_card_informations
  resources :user_payments do
    get :change_subscription, :on=> :collection
    post :save_subscription_change, :on=> :collection
    get :renew_subscription, :on=> :collection
    post :save_renew_subscription, :on=> :collection
  end
  
  resources :subscription_details do
    get :renew_subscription, :as => :renew
  end

  resources :deals_wizards do
    get :compaign_objectives, :on => :collection, :as => :objectives
    get :set_deal_wizard, :on => :collection, :as=> :set
    get :send_data, :on => :collection
  end

  resources :target_rules do
    post :show_params, :on => :collection

  end
  match '/set_params'=> 'target_rules#parameter_setup'
  resources :campaigns

  resources :deals do
    get :compaign_params, :on=> :collection
    post :upload_img, :on=> :collection
    get :set_preview, :on=> :collection
  end
  match 'save' => 'deals#save'
  resources :actions
  match "/users/actions" => "users#actions"
  get 'selectretailer', :to=>'users#select_retailer'

  devise_for :users , :controllers => {:registrations => "users"}    #Modified for Retailor

  devise_scope :user do
    resources :users  , :only => [:upload_pic, :index,:show,:new,:create, :edit,:update,:destroy,:switch,:switchbacktoadmin,:actions]    #Modified for Retailor
    get 'sign_in', :to=>'devise/sessions#new'
    delete 'sign_out', :to=>'devise/sessions#destroy'

    get 'switch', :to=>'users#switch'  #Modified for Retailor
    get 'switchbacktoadmin', :to=>'users#switchbacktoadmin'  #Modified for Retailor
    
  end
  root :to => "home#actions"

  

end

app/models/subscription_detail.rb
class SubscriptionDetail < ActiveRecord::Base
  belongs_to :plan
  belongs_to :user
  attr_accessible :balance_due, :expiry, :status, :plan_id, :user_id, :service_type, :is_active, :full_name
  scope :active, where(:is_active=>true)
end

app/controllers/subscription_details_controller.rb
class SubscriptionDetailsController < ApplicationController

  before_filter :get_plans, :only => [:new, :edit]

  def index
    @subscription_details = SubscriptionDetails.all
  end

  def show
    @subscription_detail = SubscriptionDetails.find_by_id(params[:id])
  end

  def new
    @subscription_detail = SubscriptionDetail.new
    @url = subscription_details_path
  end

  def edit
    @subscription_detail = SubscriptionDetails.find_by_user_id(params[:id])
    @url = subscription_detail_path(@subscription_detail.id)
  end
  
  def update
    @subscription_detail = SubscriptionDetail.find_by_id(params[:id])
    respond_to do |format|
      if @subscription_detail.update_attributes(params[:subscription_details])
        format.html { redirect_to user_url(current_user.id) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @subscription_detail.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def create
    @subscription_detail = SubscriptionDetail.new(params[:subscription_details])
    
      respond_to do |format|
        if @subscription_detail.save
        format.html {redirect_to user_url(current_user.id)}
        else
          format.html {render action: 'new'}
          format.json { render json: @subscription_detail.errors, status: :unprocessable_entity }
        end
      end
    
  end

#  def change_subscription_plan
#    @subscription_detail = SubscriptionDetails.new
#    @plan = Plan.all
#  end

  def renew_subscription
    @subscription_detail = SubscriptionDetails.find_by_id(params[:subscription_detail_id])
    @plan = @subscription_detail.plan
    @user = @subscription_detail.user
    
  end
  
  def save
    @subscription_detail = SubscriptionDetails.new(params[:subscription_detail])
  end

  def get_plans
    @plans = Plan.all
  end

end

app/helpers/subscription_details_helper.rb
module SubscriptionDetailsHelper
end

app/views/subscription_details/_form.html.erb
<%content_for :title, 'beam-e-up | Change Subscription'%>
<%content_for :keywords, '' %>
<%content_for :description, '' %>

<div class="content">
  <%= render :partial=> 'partials/main_menu' %>
  <div class="contentInside">
    <!-- Content goes here-->

    <%= form_for(@subscription_detail, :url=> @url) do |f| %>
      <% if @subscription_detail.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@subscription_detail.errors.count, "error") %> prohibited this Subscription details from being saved:</h2>

          <ul>
            <% @subscription_detail.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="panel">
        <div class="head"><h3>Change Subscription</h3></div>
        <div class="inside">
          Choose from One of the following Subscription Plans:<br /><br />
          <div >
  <%#*<h4 class="q1"><strong>Plan</strong></h4>&nbsp;<h4 class="q1"><strong>Pricing</strong></h4><br />%>
            <table class="subscription_table" id="full" style="display:none">
              <thead>
                <tr>
                  <td><h4><strong>Plan</strong></h4></td>
                  <td><h4><strong>Pricing</strong></h4></td>
                </tr>
              </thead>
              <tbody>
                <tr style="padding-bottom: 20px;display: block;"></tr>
                <% Plan.find_all_by_plan_type('f').each do |plan| %>
                  <tr>
                    <td>
                      <%= f.radio_button :plan_id, plan.id %><label for="platinum" ><%= "#{plan.title} - #{plan.compaigns_per_month} #{'campaigns per month' if plan.compaigns_per_month!= 'Unlimited'}" %></label>
                    </td>
                    <td>
                      <label for="<%=  plan.title %>" class="q1"  >
                        $<%= plan.price %> per month</label>
                    </td>
                  </tr>
                <%end%>
              </tbody>
            </table>

            <table class="subscription_table" id="self">
              <thead>
                <tr>
                  <td><h4><strong>Plan</strong></h4></td>
                  <td><h4><strong>Pricing</strong></h4></td>
                </tr>
              </thead>
              <tbody>
                <tr style="padding-bottom: 20px;display: block;"></tr>
                <% Plan.find_all_by_plan_type('s').each do |plan| %>
                  <tr>
                    <td>
                      <%= f.radio_button :plan_id, plan.id %><label for="platinum" ><%= "#{plan.title} - #{plan.compaigns_per_month} #{'campaigns per month' if plan.compaigns_per_month!= 'Unlimited'}" %></label>
                    </td>
                    <td>
                      <label for="<%=  plan.title %>" class="q1"  >
                        $<%= plan.price %> per month</label>
                    </td>
                  </tr>
                <%end%>
              </tbody>
            </table>


          </div>


          <div class="clear"></div><br />
          <div class="divider"></div><br />
          <%= f.radio_button :service_type, 'self',:id=>'self' ,:checked=>true%><label for="self">Self Service</label>&nbsp;&nbsp;&nbsp;&nbsp;
          <%= f.radio_button :service_type, 'full' ,:id=>'full' %><label for="full">Full Service</label><br />
        </div>
      </div>
      <div class="clear"></div>
      <%= f.hidden_field :user_id, :value=> "#{current_user.id if current_user.present?}" %>
      <%= link_to 'Back', user_path(current_user), :class => "edgyBlueButton nomargin" %>
      <span class="floatRight"><%= f.submit 'Save', :class => "edgyBlueButton nomargin link_button" %></span>

    <% end %>
    <div class="clear"></div>
    <!-- Content ends here-->
  </div>
</div>

<script type="text/javascript">
   alert('true');
  $(document).onload(function() {
    $('#plan_'+<%=@subscription_detail.plan_id%>).click();
    alert('true');
  });
</script>

app/views/subscription_details/change_subscription_plan.html.erb
<%content_for :title, 'beam-e-up | Change Subscription'%>
<%content_for :keywords, '' %>
<%content_for :description, '' %>

<div class="content">
  <%= render :partial=> 'partials/main_menu' %>
  <div class="contentInside">
    <!-- Content goes here-->
    
    <%= form_for(@subscription_detail, :url => change_subscription_details_path) do |f| %>
  <% if @subscription_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscription_detail.errors.count, "error") %> prohibited this Subscription details from being saved:</h2>

      <ul>
      <% @subscription_detail.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



 
    <div class="panel">
      <div class="head"><h3>Change Subscription</h3></div>
      <div class="inside">
        Choose from One of the following Subscription Plans:<br /><br />
        <div class="q1">
          <h4><strong>Plan</strong></h4><br />
          <% @plan.each do |plan| %>
          <%= f.radio_button :plan_id, plan.id %><label for="platinum"><%= "#{plan.title} - #{plan.compaigns_per_month} #{'campaigns per month' if plan.compaigns_per_month!= 'Unlimited'}" %></label><br />
          <%end%>
          <%#*<input name="subscription" id="platinum" value="platinum" type="radio"/><label for="platinum">Platinum - Unlimited</label><br />%>
          <%#*<input name="subscription" id="gold" value="gold" type="radio"/><label for="gold">Gold - 15 campaigns per month</label><br />%>
          <%#*<input name="subscription" id="silver" value="silver" type="radio"/><label for="silver">Silver - 10 campaigns per month</label><br />%>
          <%#*<input name="subscription" id="bronze" value="bronze" type="radio"/><label for="bronze">Bronze - 5 campaigns per month</label><br />%>
        </div>
        <div class="q1">
          <h4><strong>Pricing</strong></h4><br />
          <% @plan.each do |plan| %>
          <label for="platinum">$<%= plan.price %> per month</label><br />
          <%end%>
        </div>
        
        <div class="clear"></div><br />
        <div class="divider"></div><br />
        <%= f.radio_button :service_type, 'self' %><label for="self">Self Service</label>&nbsp;&nbsp;&nbsp;&nbsp;
        <%= f.radio_button :service_type, 'full' %><label for="full">Full Service</label><br />
        <%#*<input type="radio" name="service" id="self"/><label for="self">Self Service</label>&nbsp;&nbsp;&nbsp;&nbsp;%>
        <%#*<input type="radio" name="service" id="full"/><label for="full">Full Service</label><br />%>
      </div>
    </div>
    <div class="clear"></div>
    <a class="edgyBlueButton nomargin" onClick="window.history.go(-1)">Back</a>
    <span class="floatRight"><%= f.submit 'Save', :class => "edgyBlueButton nomargin link_button" %></span>
     
    <% end %>
    <div class="clear"></div>
    <!-- Content ends here-->
  </div>
</div>

app/views/subscription_details/edit.html.erb
<%#*<h1>Editing subscription_detail</h1>%>

<%= render 'form' %>

<%#= link_to 'Show', @subscription_detail %> |
<%#= link_to 'Back', subscription_details_path %>

app/views/subscription_details/index.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= "index.html" %>

app/views/subscription_details/new.html.erb
<%#*<h1>Add subscription_detail</h1>%>

<%= render 'form' %>

<%#= link_to 'Show', @subscription_detail %> |
<%#= link_to 'Back', subscription_details_path %>

app/views/subscription_details/renew_subscription.html.erb
<%content_for :title, 'beam-e-up | Subscription and Payment'%>
<%content_for :keywords, '' %>
<%content_for :description, '' %>


<div class="content">
  <%= render :partial=> 'partials/main_menu' %>
  <div class="contentInside">
    <!-- Content goes here-->
    <div class="panel">
      <div class="head"><h3>Subscription and Payment</h3></div>
      <div class="inside">
        <div class="q borderRight" style="width:300px; padding-right:20px;">
          <br />
          <h3>Subscribe</h3>
          <form action="#" method="post">
            <label class="static">Subscription Plan: </label><strong><%= display_value(@plan.title) %></strong><br />
            <label class="static">Subscription Expiry: </label><strong><%= display_value(@plan.expiry) %></strong><br /><br />
            Choose the Subscription Term:<br />
            <div class="clear"></div>
            <div style="width:270px;">
              <select name="term" id="term">
                <option>Subscribe 1 month - $299</option>
              </select><br />
            </div>
            <label class="static">Balance Due: </label><strong>$299</strong><br /><br /><br />
            <%= link_to 'Change Subscription Plan', edit_subscription_detail_url(@user.id), :class => "edgyBlueButton  nomargin"%>
            <%#*<a class="edgyBlueButton nomargin" href="#">Change Subscription Plan</a>%>
            <br /><br />
          </form>
        </div>

        <div class="q" style="width:560px; margin-top:-10px; margin-right:0px;">
          <br />
          <h3>Payment Options</h3>
          <div class="q" style="width:320px;">
            <h3>Credit Card</h3>
            <label class="static" for="name">Name: </label><input type="text" name="name" id="name" style="width:150px;"/><br /><br />
            <label class="static" for="cardNumber">Card Number: </label><input type="text" name="cardNumber" id="cardNumber" style="width:150px;"/><br /><br />
            <label class="static" for="expireDate">Expire Date: </label><input type="text" name="expireDate" id="expireDate" style="width:150px;"/>
          </div>
          <div class="q nomargin" style="width:180px;">
            <h3>PayPal</h3>
            <a href="#"><img src="images/paypal.png" width="143" height="60" alt="PayPal"/></a>
          </div>

          <div class="clear"></div><br />
          <span style="margin-top:10px; display:block;"><a class="edgyBlueButton nomargin" href="#">Submit</a></span><br />
        </div>
      </div>

      <div class="clear"></div>
    </div>

    <div class="clear"></div>
    <!-- Content ends here-->
  </div>
</div>

app/views/subscription_details/show.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= "show.html" %>