config/routes.rb
BeemUp::Application.routes.draw do

  namespace :admin do
    resources :questions
    resources :zones
    resources :classifieds
    resources :users
    resources :bases
    resources :hotspots
    resources :reports do 
      get :retailers_list, :on => :member
      get :deals_list, :on => :member
    end
  end

  resources :contactus

  resources :archive_contents
  namespace :api do namespace :v1 do
      resources :classified do
        get :get_classifieds, :on => :collection
      end
      resources :users do
        post :sign_up, :action => :create, :on => :collection
        post :update_profile, :action => :update, :on => :collection
        get :delete, :action => :delete_profile, :on => :collection
        get :profile, :on => :collection
        get :token_key, :on => :collection

      end
      resources :questions do
        get :question, :action => :question_of_the_day, :on => :collection
        post :answer, :action => :send_answers, :on => :collection
        
      end
      resources :target_rules
      
      resources :deals do
        get :search, :on => :collection
        get :coupons, :on => :collection
        get :my_coupons, :on => :collection
        get :last_minute_deals, :on => :collection
        get :gifts_or_seasonal_deals, :on => :collection
        get :generate_coupons, :on => :collection
      end
      post '/redeem_coupon/redeem' => 'redeemed_deals#redeem'
      resources :stores do
        get :all , :action => :stores, :on => :collection
      end
      resources :store_categories do
        get :stores, :on => :collection
      end
      resources :categories do
        get :all , :action => :categories, :on => :collection
      end
      resources :user_categories do
        get :categories, :on => :collection
        post :save, :action => :saveUserCategories, :on => :collection

      end
      resources :user_stores do
        get :stores, :on => :collection
        post :save,  :action => :saveUserStores, :on => :collection

      end
      
      resources :wallets do
        get :coupon,  :action => :save_coupon, :on => :collection
        get :mywallet,  :action => :my_wallet, :on => :collection
        get :redeem, :on=> :collection
      end
     
      
    end  end # /api/v1/

  
  resources :temp_images
  resources :temp_users
  resources :credit_card_informations
  resources :user_payments do
    get :change_subscription, :on=> :collection
    post :save_subscription_change, :on=> :collection
    get :renew_subscription, :on=> :collection
    post :save_renew_subscription, :on=> :collection
  end
  
  resources :subscription_details do
    get :renew_subscription, :as => :renew
  end

  resources :deals_wizards do
    get :compaign_objectives, :on => :collection, :as => :objectives
    get :set_deal_wizard, :on => :collection, :as=> :set
    get :send_data, :on => :collection
  end

  resources :target_rules do
    post :show_params, :on => :collection

  end
  match '/set_params'=> 'target_rules#parameter_setup'
  resources :campaigns

  resources :deals do
    get :compaign_params, :on=> :collection
    post :upload_img, :on=> :collection
    get :set_preview, :on=> :collection
  end
  match 'save' => 'deals#save'
  resources :actions
  match "/users/actions" => "users#actions"
  get 'selectretailer', :to=>'users#select_retailer'

  devise_for :users , :controllers => {:registrations => "users"}    #Modified for Retailor

  devise_scope :user do
    resources :users  , :only => [:upload_pic, :index,:show,:new,:create, :edit,:update,:destroy,:switch,:switchbacktoadmin,:actions]    #Modified for Retailor
    get 'sign_in', :to=>'devise/sessions#new'
    delete 'sign_out', :to=>'devise/sessions#destroy'

    get 'switch', :to=>'users#switch'  #Modified for Retailor
    get 'switchbacktoadmin', :to=>'users#switchbacktoadmin'  #Modified for Retailor
    
  end
  root :to => "home#actions"

  

end

app/views/partials/_admin_menu.html.erb
<div class="contentHeader">
  <div class="search" style="visibility:hidden;">
    <input type="text" placeholder="Type here to search..."/>
    <a class="searchBlueButton" href="#">Search</a>
  </div>
  <div class="menu">
    <ul>
      <li class="selected mainmenu"><a href="#">Site Users</a></li>
      <li class="mainmenu"><a href="#">Stores</a></li>
      <li class="mainmenu"><a href="#">Categories</a></li>
      <li class="mainmenu"><a href="#">Contact</a></li>
    </ul>
  </div>
</div>

app/views/partials/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation" class="flash error">
      <h2><%= pluralize(object.errors.count, "error") %>
        prohibited this <%= object.class.to_s.underscore.humanize.downcase %>
        from being saved:</h2>
      <p>There were problems with the following fields:</p>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/partials/_flashes.html.erb
  <%  if flash[:notice] %>
    <div class=" notification success hideable">
      <p>
        <%= flash[:notice].to_s.html_safe %>
      </p>
    </div>
  <%end%>
  <% if flash[:error] %>
    <div class=" notification failure hideable">
      <p>
        <%= flash[:error]%>
      </p>
    </div>
  <%end%>
        

app/views/partials/_main_menu.html.erb
<div class="contentHeader">
  <div class="search"  style="visibility:hidden;">
    <input type="text" placeholder="Type here to search..." style="width: 150px;"/>
    <a class="searchBlueButton" href="#">Search</a>
  </div>
   <% activetab=0 %>
  <% if (params[:controller]=="pages" && params[:action]=="0" ) %>
      <% activetab=0 %>
  <% elsif (params[:controller]=="deals" && params[:action]=="new" ) %>
          <% activetab=1 %>
  <% elsif (params[:controller]=="deals" && params[:action]=="index" ) %>
      <% activetab=2 %>
  <% elsif (params[:controller]=="users" && params[:action]=="show"  )  %>
      <% activetab=3 %>
  <% elsif (params[:controller]=="contactus" && params[:action]=="new" )  %>
      <% activetab=4 %>
  <% elsif (params[:controller]=="admin/zones" )  %>
      <% activetab=5 %>
  <% elsif (params[:controller]=="admin/classifieds" )  %>
      <% activetab=6 %>
  <% elsif (params[:controller]=="admin/questions"  )  %>
      <% activetab=7 %>
  <% elsif (params[:controller]=="contactus" && params[:action]=="new" )  %>
      <% activetab=8 %>
      <% elsif (params[:controller]=="admin/hotspots"  )  %>
      <% activetab=9 %>
  <% end %>
  <div class="menu">
    <ul>
      <% if current_user.role_id==Role::ADMIN_USER_ID	  %>
          <li class="<%= activetab==5? "selected": "" %>"><%= link_to 'Zones', admin_zones_url %></li>
          <li class="<%= activetab==0 && !current_page?(admin_reports_path) ? "selected": "" %>"><%= link_to 'Retailers', users_url %></li>
          <!--<li class="<%#= activetab==1? "selected": "" %>"><%#= link_to 'Develop a Campaign', new_deal_url %></li>
          <li class="<%#= activetab==2? "selected": "" %>"><%#= link_to 'Manage Campaigns', deals_url %></li> -->
          <li class="<%= activetab==6? "selected": "" %>"><%= link_to 'Classifieds', admin_classifieds_path %></li>
          <li class="<%= "selected" if current_page?(admin_reports_path) %>"><%= link_to "Reports", admin_reports_path %></li>
          <li class="<%= activetab==9? "selected": "" %>"><%= link_to 'Hotspots', admin_hotspots_path %></li>

          <li class="<%= activetab==7? "selected": "" %>"><%= link_to 'Question of the Day', admin_questions_path %></li>
      <% else %>
          <li class="<%= activetab==1? "selected": "" %>"><%= link_to 'Develop a Campaign', new_deal_url %></li>
          <li class="<%= activetab==2? "selected": "" %>"><%= link_to 'Manage Campaigns', deals_url %></li>
          <li class="<%= activetab==3? "selected": "" %>"><%= link_to 'My Account', user_url(:id => current_user.id) %></li>
          <li class="<%= activetab==4? "selected": "" %>"><%= link_to 'Contact', new_contactu_url %></li>
      <% end %>
    </ul>
  </div>
</div>

  

app/views/partials/_shared_layout.html.haml
=# javascript_include_tag(:uploadify)
=# session_meta_tag
-#%h1{:style=>'color:white; position absolute;'}'ABsdfadfsa'
    