config/routes.rb
BeemUp::Application.routes.draw do

  namespace :admin do
    resources :questions
    resources :zones
    resources :classifieds
    resources :users
    resources :bases
    resources :hotspots
    resources :reports do 
      get :retailers_list, :on => :member
      get :deals_list, :on => :member
    end
  end

  resources :contactus

  resources :archive_contents
  namespace :api do namespace :v1 do
      resources :classified do
        get :get_classifieds, :on => :collection
      end
      resources :users do
        post :sign_up, :action => :create, :on => :collection
        post :update_profile, :action => :update, :on => :collection
        get :delete, :action => :delete_profile, :on => :collection
        get :profile, :on => :collection
        get :token_key, :on => :collection

      end
      resources :questions do
        get :question, :action => :question_of_the_day, :on => :collection
        post :answer, :action => :send_answers, :on => :collection
        
      end
      resources :target_rules
      
      resources :deals do
        get :search, :on => :collection
        get :coupons, :on => :collection
        get :my_coupons, :on => :collection
        get :last_minute_deals, :on => :collection
        get :gifts_or_seasonal_deals, :on => :collection
        get :generate_coupons, :on => :collection
      end
      post '/redeem_coupon/redeem' => 'redeemed_deals#redeem'
      resources :stores do
        get :all , :action => :stores, :on => :collection
      end
      resources :store_categories do
        get :stores, :on => :collection
      end
      resources :categories do
        get :all , :action => :categories, :on => :collection
      end
      resources :user_categories do
        get :categories, :on => :collection
        post :save, :action => :saveUserCategories, :on => :collection

      end
      resources :user_stores do
        get :stores, :on => :collection
        post :save,  :action => :saveUserStores, :on => :collection

      end
      
      resources :wallets do
        get :coupon,  :action => :save_coupon, :on => :collection
        get :mywallet,  :action => :my_wallet, :on => :collection
        get :redeem, :on=> :collection
      end
     
      
    end  end # /api/v1/

  
  resources :temp_images
  resources :temp_users
  resources :credit_card_informations
  resources :user_payments do
    get :change_subscription, :on=> :collection
    post :save_subscription_change, :on=> :collection
    get :renew_subscription, :on=> :collection
    post :save_renew_subscription, :on=> :collection
  end
  
  resources :subscription_details do
    get :renew_subscription, :as => :renew
  end

  resources :deals_wizards do
    get :compaign_objectives, :on => :collection, :as => :objectives
    get :set_deal_wizard, :on => :collection, :as=> :set
    get :send_data, :on => :collection
  end

  resources :target_rules do
    post :show_params, :on => :collection

  end
  match '/set_params'=> 'target_rules#parameter_setup'
  resources :campaigns

  resources :deals do
    get :compaign_params, :on=> :collection
    post :upload_img, :on=> :collection
    get :set_preview, :on=> :collection
  end
  match 'save' => 'deals#save'
  resources :actions
  match "/users/actions" => "users#actions"
  get 'selectretailer', :to=>'users#select_retailer'

  devise_for :users , :controllers => {:registrations => "users"}    #Modified for Retailor

  devise_scope :user do
    resources :users  , :only => [:upload_pic, :index,:show,:new,:create, :edit,:update,:destroy,:switch,:switchbacktoadmin,:actions]    #Modified for Retailor
    get 'sign_in', :to=>'devise/sessions#new'
    delete 'sign_out', :to=>'devise/sessions#destroy'

    get 'switch', :to=>'users#switch'  #Modified for Retailor
    get 'switchbacktoadmin', :to=>'users#switchbacktoadmin'  #Modified for Retailor
    
  end
  root :to => "home#actions"

  

end

app/helpers/api/v1/deal_helper.rb
module Api::V1::DealHelper
end

app/helpers/api/v1/deals_helper.rb
module Api::V1::DealsHelper
end

app/helpers/deals_helper.rb
module DealsHelper

  def self.get_back_image_url(deal,temp_img)

    if temp_img.present? and temp_img.logo_image.present?
      url = self.url_getter(temp_img.logo_image)
    elsif deal.present? and deal.background_image.present?
      
      url = self.url_getter(deal.background_image)
    else
      return ''
#      return '/supportive_image/noimage.png'
    end

    return url
  end

  

  def self.url_getter(img)
     img.url(:original).split('?')[0]
  end
  def url_generator(img)
    return img.url(:original).split('?')[0]
  end
  
  def get_item_img_url(deal,temp_img)
    if temp_img.present? and temp_img.thing_image.present?
       url= temp_img.thing_image.present? ? url_generator(temp_img.thing_image) : ''
    elsif deal.present? and deal.item_image.present?
       url = deal.item_image.present? ? url_generator(deal.item_image) : ''
    else
      return ""
    end
    return url
  end
  
  def get_retailer_img_url(deal,temp_img)
    if temp_img.present? and  temp_img.retail_image.present?
       url= temp_img.retail_image.present? ?  url_generator(temp_img.retail_image) : ''
    elsif deal.present? and deal.retailer_image.present?
       url = deal.retailer_image.present? ?  url_generator(deal.retailer_image) : ''
    else
      return ""
    end
    return url
  end
  
  def get_front_img_url(deal,temp_img)
    if temp_img.present? and (temp_img.thing_image.present? or temp_img.retail_image.present?)
       url= temp_img.thing_image.present? ? url_generator(temp_img.thing_image) : url_generator(temp_img.retail_image)
    elsif deal.present? and (deal.item_image.present? or deal.retailer_image.present?)
       url = deal.item_image.present? ? url_generator(deal.item_image) : url_generator(deal.retailer_image)
    else
      return ""
    end
    return url
  end
  # to get coupon retailer image container css to show image accordingly
  def retailer_image_container_css(deal, temp_img)

    if temp_img.present? and temp_img.front_image_container_css.present?
      temp_img.front_image_container_css
    elsif deal.present? and deal.front_image_container_css.present?
      deal.front_image_container_css
    else
      'width:163px; height:144px;'
    end
  end
  # to get coupon item image container css to show image accordingly
  def item_image_container_css(deal, temp_img)

    if temp_img.present? and temp_img.item_image_container_css.present?
      temp_img.item_image_container_css
    elsif deal.present? and deal.item_image_container_css.present?
      deal.item_image_container_css
    else
      'width: 163px; height: 144px;'
    end
  end
  def description_css(deal, temp_img)

    if temp_img.present? and temp_img.description_css.present?
      temp_img.description_css
    elsif deal.present? and deal.description_css.present?
      deal.description_css
    else
      'width: 163px; height: 144px;'
    end
  end



  def set_text(deal_wizard)
     offer_arr = DealsHelper.get_coupen_offer(deal_wizard)
     offer_text = ""
     offer_arr.each do |offer|
        offer_text += "#{offer}\n\r"
      end
      return offer_text
  end
  def self.check_type?(value)

    if value.present? and (value.class== Fixnum or value.class== Float)
      return true
    else
      return false
    end

  end



  def description_style(deal,tmp_img)

    style = ""
    
    style += description_css(deal,tmp_img)

    if session[:deal_bold]=='true' or ( session[:deal_bold].blank? and deal.bold)
      style += "font-weight: bold;"
    elsif session[:deal_bold]=='false'
      style += "font-weight: normal;"
    end
    if session[:deal_italic]=='true'or ( session[:deal_italic].blank? and deal.italic)
      style += "font-style: italic;" 
    elsif session[:deal_italic]=='false'
        style += "font-style: normal;" 
    end

     if session[:deal_underline]=='true' or ( session[:deal_underline].blank? and deal.underline)
       style += "text-decoration: underline;"
     elsif session[:deal_underline]=='false'
      style += "text-decoration: none;"
     end
    
    style += "font-size: #{session[:deal_font_size]}px;" if session[:deal_font_size].present?
    style += "font-size: #{deal.font_size}px;" if ( session[:deal_font_size].blank? and deal.font_size)

    style += "font-family: #{session[:deal_font_name]};" if session[:deal_font_name].present?
    style += "font-family: #{deal.font_name};" if  ( session[:deal_font_name].blank? and deal.font_name)

    style += "color: #{session[:deal_font_color]};" if session[:deal_font_color].present?
    style += "color: #{deal.font_color};" if ( session[:deal_font_color].blank? and deal.font_color)
    
    
    style
  end

  def get_back_color(session_color, deal)

    if session_color.present?
      session_color
    elsif deal.present? and deal.background_color.present?
      deal.background_color
    else
      '#f7f7f7'
    end
  end
  
  def preveiw_style(img, deal)
    style = ""
    style = "background-color:white;"
     #todo [taimoor noticed] in show preview have to manange this background color and image
#      style += ((session[:back_image]=="true" and img.blank?)  ? "background: #{session[:deal_background_color].blank? ? deal.background_color : session[:deal_background_color]};" : "background: url('"+img+"') no-repeat;"
    if (session[:back_image]=="true"  or session[:back_image].blank?) and img.present?
    style += "background: url('"+img+"') no-repeat;"
    else
      style +=    session[:deal_background_color].present? ? "background-color: #{get_back_color(session[:deal_background_color], deal)}!important;" : "background-color: #{(deal.try(:background_color) || "white" )} ;"
    end

  #style += (session[:back_image]=="true"  and img.present?)  ? "background: url('"+img+"') no-repeat;" : "background-color: #{session[:deal_background_color].blank? ? ((deal.present? and deal.background_color.present?) ? deal.background_color : 'rgb(245, 245, 245)') : session[:deal_background_color]}!important;"
  #      style += session[:back_image]=="true" ? "background: url('"+img+"') no-repeat;" : "background: #{cookies[:background_color]};"
      style += "background-size: 300px 300px!important;"
      style += "width:300px!important; height: 300px!important;"
      style += "max-width:300px!important; max-height: 300px!important;text-align: center;"
    style
    
  end

  def get_check_box(name, value)
#html = ''
    if(value == true)
#      <input type=checkbox name=deal[#{name}] id=deal_#{name} value=1 checked=checked />
#     html << "<%= f.check_box :#{name},{:checked => 'checked'} %>"

#    "<%= f.check_box :bold,{:checked => 'checked'} %>"
    else
#      "<input type=checkbox name=deal[#{name}] id=deal_#{name} value=1  />"
#     html <<  "<%= f.check_box :#{name}%>"
    end
#return html
  end

  def campaign_title(deal)
    (deal.target_rule.present? and deal.target_rule.name.present?) ? deal.target_rule.name : 'Campaign Name Here'
  end

  def get_value(cookie_value, db_value)
    cookie_value.present? ? cookie_value : db_value
  end
  def get_font_color(cookie_value= session[:deal_font_color], db_value=nil)
    font_color = cookie_value.present? ? cookie_value : db_value
    if font_color.blank?
      font_color = '#000000'
    end
    return font_color
  end
#  def get_font_color
#  session[:deal_font_color].present? ? session[:deal_font_color] : '#000000'
#end

  def get_description(deal)
    description = session[:deal_description].present? ? session[:deal_description] : deal.description
    if description.present?
      description_arr = description.split("\n");
      description_string=''
      description_arr.each do |arr|
        description_string = description_string+arr+"<br/>"
      end
      return description_string.html_safe
    else
      ''
    end

  end



  def get_coupen_offer

    if  session[:compaign_objectives_id].present?
      objective_id = session[:compaign_objectives_id]
      objective_hash = session[objective_id.to_sym] if objective_id.present?
      #    puts "objective_hash=#{objective_hash.inspect}"
      if objective_hash.present?
        sub_head_id = objective_hash['0']
        #       puts "sub_head_id==#{sub_head_id}------objective_hash[sub_head_id]=#{objective_hash[sub_head_id]}"
         if sub_head_id.present? and objective_hash[sub_head_id].present?
           selected_sub_obj = "#{sub_head_id+'_'+objective_hash[sub_head_id]}"
           get_text(objective_hash, objective_id, sub_head_id, objective_hash[sub_head_id], selected_sub_obj)
         else
          return ''
         end
      else
        return ''
      end
    else
      ""
    end
    
  end

  def get_text(objective_hash, objective_id, sub_head_id, selected_sub_obj_id, selected_sub_obj)

    case (objective_id)
    when '1'
      first_objective(objective_hash, objective_id, sub_head_id, selected_sub_obj_id, selected_sub_obj)
    when '2'
      second_objective(objective_hash, objective_id, sub_head_id, selected_sub_obj_id, selected_sub_obj)
    when '3'
      third_objective(objective_hash, objective_id, sub_head_id, selected_sub_obj_id, selected_sub_obj)
    when '4'
      fourth_objective(objective_hash, objective_id, sub_head_id, selected_sub_obj_id, selected_sub_obj)
    when '5'
      fifth_objective(objective_hash, objective_id, sub_head_id, selected_sub_obj_id, selected_sub_obj)
    else
      ""
    end
    
  end

  def first_objective(objective_hash, objective_id, sub_head_id, selected_sub_obj_id, selected_sub_obj)
    #      puts  "in first object check it yar :D sub_head_id=#{sub_head_id}, selected_sub_obj_id=#{selected_sub_obj_id.inspect}, selected_sub_obj=#{selected_sub_obj.inspect}"
    #      puts "chec :DD>>>> #{session[objective_id.to_sym][selected_sub_obj]}"
    #      puts "chec :DD>>>> #{session[objective_id.to_sym][selected_sub_obj]['1']} and get #{session[objective_id.to_sym][selected_sub_obj]['2']} free!"
    case(sub_head_id)
    when '1'
      case(selected_sub_obj_id)
      when '1'
        return "Buy one, get one free!"

app/views/deals/_checkbox.html.erb
<%= puts "value=========#{value.inspect}====#{name.inspect}" %>
<%if value== "true"%>
<input id="<%= "deal_#{name}" %>" name="<%= "deal[#{name}]" %>" type="checkbox" value="1" style="opacity: 0;" checked='checked' />
<%else%>
<input id= "<%= "deal_#{name}" %>" name="<%= "deal[#{name}]" %>" type="checkbox" value="1" style="opacity: 0;"  />

<%end%>

app/views/deals/edit.html.erb
<%content_for :title, 'beam-e-up | Coupon Creation'%>
<%content_for :keywords, '' %>
<%content_for :description, '' %>
  <%= stylesheet_link_tag    "/stylesheets/colorpicker/colorpicker", :media => "all" %>
  <%= stylesheet_link_tag    "/stylesheets/colorpicker/layout", :media => "all" %>


    <div class="content">
      <%= render :partial=> 'partials/main_menu' %>
      <div class="contentInside">
        <!-- Content goes here-->
        <div class="steps">
          <div class="step current one">
            <div class="number">1</div><br /><br />Coupon Creation
          </div>
          <div class="step two">
            <div class="number">2</div><br /><br />Campaign Parameters Setup
          </div>
          <div class="step three">
            <div class="number">3</div><br /><br />Review &amp; Submit
          </div>
        </div>

        <div class="panel">
          <%= render :partial => 'temp_images' %>
          
          <%= form_for(@deal, :url => compaign_params_deals_path, :html=>{:method => :get, :onsubmit=>'set_color()', :id=>:deal_form, :class=>:deal_form}) do |f| %>
          <div class="head"><h3>Coupon Creation</h3></div>
          <% if @deal.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@deal.errors.count, "error") %> prohibited this deal from being saved:</h2>

                <ul>
                  <% @deal.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

          
          <%= hidden_field_tag :deal_id, @deal.id%>
          <div class="inside nopadding">
            <div class="q" style="width: 586px;">
              <div class="plain">
                <h3>Background</h3>
                <div>
                <label>Select a Background Image:</label>
                 <% if session[:back_image]=="true" or session[:back_image].blank? %>
                  <%= f.radio_button :back_image_or_color, true, {:checked => true,:class=>'radio_b  preview_change'} %>
                 <%else%>
                  <%= f.radio_button :back_image_or_color, true, {:class=>'radio_b  preview_change'} %>
                 <%end%>
                
                <input type="button" id="upload" name="upload" value="Upload Image" class='edgyBlueButton cookie_setter' onclick="upload_img($(this)); set_background(true);" />
                <% if  session[:back_image]=='false' %>
                  <%= f.radio_button :back_image_or_color, false, {:checked => true,:class=>'radio_b'} %>
                <%else%>
                  <%= f.radio_button :back_image_or_color, false, :class=>'radio_b' %>
                <%end%>
               
                <label>Or Select background color:</label>
                <div id="colorSelector"><div style="background-color: #fff"></div></div>
                <%= f.hidden_field :background_color, :value=>session[:deal_background_color], :class=>'preview_change'  %>
                </div>
                <div class="spacer"></div>

                <div class="divider"></div><br />

                <div class="q" style="width:500px;">
                  <h3>Add Text Descriptions/Coupon Terms</h3>
                  <input type="hidden" name="offer_description" id="offer_description" value="<%= get_coupen_offer %>"/>
                  <%= f.text_area :description, :cols => 80, :rows => 6, :placeholder=>'Enter Your text here', :value => session[:deal_description], :class => 'preview_change' %>
                </div>

                <div class="q nomargin" style="width:250px;">
                  <h3>Font</h3>
                    <div class="q" style="width:100px;">
                      <%= f.select :font_name, ['helvetica','Times New Roman'] ,{:selected => @deal.font_name} ,{ :class => 'preview_change'} %>
                    </div>
                    <div class="q" style="width:50px;">
                      <%= f.text_field :font_color, :class => " preview_change color {hash:true,caps:false}", :value => get_font_color(session[:deal_font_color], @deal.font_color) %>
                    </div>
                    <div class="q nomargin custom_selector" style="width:60px;">
                      <%= f.select :font_size, ['10','11','12','13'],{:selected => @deal.font_size}, {:class => 'preview_change'} %>
                    </div><br />
                    
                    <% if session[:deal_bold]=="true" %>
                    <%= f.check_box :bold,{:checked => 'checked', :class => 'preview_change'} %>
                    <%else%>
                      <%= f.check_box :bold, :class => 'preview_change' %>
                    <%end%>
                    <%= f.label :bold %>&nbsp;&nbsp;&nbsp;
                    <% if session[:deal_italic]=="true" %>
                    <%= f.check_box :italic,{:checked => 'checked', :class => 'preview_change'} %>
                    <%else%>
                      <%= f.check_box :italic, :class => 'preview_change' %>
                    <%end%>
                    <%= f.label :italic %>&nbsp;&nbsp;&nbsp;
                    <% if session[:deal_underline]=="true" %>
                    <%= f.check_box :underline,{:checked => 'checked', :class => 'preview_change'} %>
                    <%else%>
                      <%= f.check_box :underline, :class => 'preview_change' %>
                    <%end%>
                    <%= f.label :underline %>&nbsp;&nbsp;&nbsp;
                    <br /><br />

                    
                    <%= link_to 'Deal Wizard', objectives_deals_wizards_path(:deal_id => @deal.id), :class=>"edgyBlueButton nomargin cookie_setter" %>
                    <div class="clear"></div><br />

                </div>
                <div class="divider"></div><br />
                <%= render :partial => 'upload_item_retailer_image' %>

                <h3>Coupon Name</h3>
                <label for="couponName">Coupon Name:</label>
                <%= f.text_field :title,  {:placeholder=>'New Coupon',:value=> get_value(cookies[:deal_title], @deal.title), :style=>"width:200px; margin-left:20px;" }  %>
               
                <div class="clear"></div>
              </div>
            </div>

            <div class="q" style="width:300px!important; height:300px!important; text-align:center;">
              <br />
              <%#*<input type="button" id="preview" name="preview" value="Preview" class='edgyBlueButton nomargin' onclick="preview_coupen($(this))"/>%>
              <br /><br />
              <%#*<iframe id="preview_form" width='240px;' height='200px;' src="/deals/set_preview"></iframe>%>
              <div class="preview" style="background-color:rgb(245, 245, 245)">
                <%= render :partial => 'preview', :locals=>{:deal => @deal, :tmp_img => @tmp_img, :deal_wizard => @deal_wizard} %>
                <input type="hidden" id="new_deal" name="new_deal" value="false"/>
              </div>
            </div>
            <%= link_to 'Archive Content', archive_contents_path, :class=>"edgyBlueButton floatRight", :style=>"clear: both;margin-bottom: 15px;margin-right: 100px" %>
            <div class="clear"></div>
            <div class="clear"></div>
          </div>
        </div>

        <div class="floatRight">
          <%= f.submit 'Next', :class=>"nextbutton nomargin cookie_setter"  %>
        </div>
 <%end%>
        <div class="clear"></div>
        <!-- Content ends here-->
      </div>
    </div>

<script type="text/javascript">

  $(function(){
    save_session();

  });

  
</script>

app/views/deals/new.html.erb
  <%= stylesheet_link_tag    "/stylesheets/colorpicker/colorpicker", :media => "all" %>
  <%= stylesheet_link_tag    "/stylesheets/colorpicker/layout", :media => "all" %>
<%content_for :title, 'beam-e-up | Coupon Creation'%>
<%content_for :keywords, '' %>
<%content_for :description, '' %>



    <div class="content">
      <%= render :partial=> 'partials/main_menu' %>
      <div class="contentInside">
        <!-- Content goes here-->
        <div class="steps">
          <div class="step current one">
            <div class="number">1</div><br /><br />Coupon Creation
          </div>
          <div class="step two">
            <div class="number">2</div><br /><br />Campaign Parameters Setup
          </div>
          <div class="step three">
            <div class="number">3</div><br /><br />Review &amp; Submit
          </div>
        </div>

        <div class="panel">
          <%= render :partial => 'temp_images' %>

          <%= form_for(@deal, :url => compaign_params_deals_path, :html=>{ :method => :get, :onsubmit=>'set_color()', :id=>:deal_form, :class=>:deal_form}) do |f| %>
          <div class="head"><h3>Coupon Creation</h3></div>
          <% if @deal.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@deal.errors.count, "error") %> prohibited this deal from being saved:</h2>

                <ul>
                  <% @deal.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
  
           <%= hidden_field_tag :deal_id %>
          <div class="inside nopadding">
            <div class="q" style="width: 586px;">
              <div class="plain">
                <h3>Background</h3>
                <div>
                <label>Select a Background Image:</label>
                <% if session[:back_image]=="true" or session[:back_image].blank? %>
                <%= f.radio_button :back_image_or_color, true, {:checked => true,:class=>'radio_b preview_change'} %>
                <%else%>
                <%= f.radio_button :back_image_or_color, true, {:class=>'radio_b preview_change'} %>
                <%end%>
               <input type="button" id="upload" name="upload" value="Upload Image" class='edgyBlueButton cookie_setter' onclick="upload_img($(this)); "/>
               <%#*<input type="button" id="upload" name="upload" value="Upload Image" class='edgyBlueButton cookie_setter' onclick="upload_img($(this)); set_background(true);"/>%>
                <% if  session[:back_image]=='false' %>
                  <%= f.radio_button :back_image_or_color, false, {:checked => true,:class=>'radio_b'} %>
                <%else%>
                  <%= f.radio_button :back_image_or_color, false, :class=>'radio_b' %>
               <%end%>
                <label>Or Select Background Color:</label>
                <div id="colorSelector" ><div style="background-color: #ffffff"></div></div>
                <%= f.hidden_field :background_color, :value => session[:deal_background_color], :class=>'preview_change'  %>
                </div>
                <div class="spacer"></div>
                
                <div class="divider"></div><br />

                <div class="q" style="width:500px;">
                  <h3>Add Text Descriptions/Coupon Terms</h3>
                  <input type="hidden" name="offer_description" id="offer_description" value="<%= get_coupen_offer %>"/>
                  <%= f.text_area :description, :cols => 60, :rows => 6, :placeholder=>'Enter Your text here', :value => session[:deal_description], :class => "preview_change"%>
                </div>

                <div class="q nomargin" style="width:250px;">
                  <h3>Font</h3>
                    <div class="q" style="width:100px;">
                      <%= f.select :font_name, ['helvetica','Times New Roman'] ,{} ,{:value => session[:deal_font_name], :class => 'preview_change'}%>
                    </div>
                    <div class="q" style="width:50px;">
                      <%= f.text_field :font_color, :class => " preview_change color {hash:true,caps:false}", :value => get_font_color %>
                    </div>
                    <div class="q nomargin custom_selector" style="width:60px;">
                      <%= f.select :font_size, ['10','11','12','13'],{:selected => session[:deal_font_size]}, { :class => 'preview_change'} %>
                    </div><br />
                    <% if session[:deal_bold]=="true" %>
                    <%= f.check_box :bold,{:checked => 'checked', :class => 'preview_change'} %>
                    <%else%>
                      <%= f.check_box :bold, :class => 'preview_change' %>
                    <%end%>
                    <%= f.label :bold %>&nbsp;&nbsp;&nbsp;
                    <% if session[:deal_italic]=="true" %>
                    <%= f.check_box :italic,{:checked => 'checked', :class => 'preview_change'} %>
                    <%else%>
                      <%= f.check_box :italic, :class => 'preview_change' %>
                    <%end%>
                    <%= f.label :italic %>&nbsp;&nbsp;&nbsp;
                    <% if session[:deal_underline]=="true" %>
                    <%= f.check_box :underline,{:checked => 'checked', :class => 'preview_change'} %>
                    <%else%>
                      <%= f.check_box :underline, :class => 'preview_change' %>
                    <%end%>
                    <%= f.label :underline %>&nbsp;&nbsp;&nbsp;
                    <br /><br />
                    
                    <%= link_to 'Deal Wizard', objectives_deals_wizards_path, :class=>"edgyBlueButton nomargin cookie_setter" %>

                    <div class="clear"></div><br />
                
                </div>
                <div class="divider"></div><br />
                <%= render :partial => 'upload_item_retailer_image' %>

                <h3>Coupon Name</h3>
                <label for="couponName">Coupon Name:</label>
                <%= f.text_field :title, :placeholder=>'New Coupon', :value=>cookies[:deal_title], :style=>"width:200px; margin-left:20px;"  %>
                <div class="clear"></div>
              </div>
            </div>

            <div class="q" style="width:300px!important; height:300px!important; text-align:center;">
              <br />
              <%#*<input type="button" id="preview" name="preview" value="Preview" class='edgyBlueButton nomargin' onclick="preview_coupen($(this))"/>%>
              <br /><br />
              
                  <div class="preview" style="background-color:rgb(245, 245, 245)" >
                    <%= render :partial => 'preview', :locals=>{:deal => @deal, :tmp_img => @tmp_img, :deal_wizard => @deal_wizard} %>
                    <input type="hidden" id="new_deal" name="new_deal" value="true"/>
                  </div>
                  <%#*<input type="hidden" id="html_data" name="html_data" />%>
              
              
            </div>
            <%= link_to 'Archive Content', archive_contents_path, :class=>"edgyBlueButton floatRight", :style=>"clear: both;margin-bottom: 15px;margin-right: 100px" %>
            <div class="clear"></div>
          </div>
         
        </div>

        <div class="floatRight">
          <%= f.submit 'Next', :class=>"nextbutton nomargin cookie_setter" ,:style =>'width:70px'%>
        </div>
 <%end%>
        <div class="clear"></div>
        <!-- Content ends here-->
      </div>
    </div>
<script type="text/javascript">

  $(function(){
    save_session();
  });
</script>