config/routes.rb
BeemUp::Application.routes.draw do

  namespace :admin do
    resources :questions
    resources :zones
    resources :classifieds
    resources :users
    resources :bases
    resources :hotspots
    resources :reports do 
      get :retailers_list, :on => :member
      get :deals_list, :on => :member
    end
  end

  resources :contactus

  resources :archive_contents
  namespace :api do namespace :v1 do
      resources :classified do
        get :get_classifieds, :on => :collection
      end
      resources :users do
        post :sign_up, :action => :create, :on => :collection
        post :update_profile, :action => :update, :on => :collection
        get :delete, :action => :delete_profile, :on => :collection
        get :profile, :on => :collection
        get :token_key, :on => :collection

      end
      resources :questions do
        get :question, :action => :question_of_the_day, :on => :collection
        post :answer, :action => :send_answers, :on => :collection
        
      end
      resources :target_rules
      
      resources :deals do
        get :search, :on => :collection
        get :coupons, :on => :collection
        get :my_coupons, :on => :collection
        get :last_minute_deals, :on => :collection
        get :gifts_or_seasonal_deals, :on => :collection
        get :generate_coupons, :on => :collection
      end
      post '/redeem_coupon/redeem' => 'redeemed_deals#redeem'
      resources :stores do
        get :all , :action => :stores, :on => :collection
      end
      resources :store_categories do
        get :stores, :on => :collection
      end
      resources :categories do
        get :all , :action => :categories, :on => :collection
      end
      resources :user_categories do
        get :categories, :on => :collection
        post :save, :action => :saveUserCategories, :on => :collection

      end
      resources :user_stores do
        get :stores, :on => :collection
        post :save,  :action => :saveUserStores, :on => :collection

      end
      
      resources :wallets do
        get :coupon,  :action => :save_coupon, :on => :collection
        get :mywallet,  :action => :my_wallet, :on => :collection
        get :redeem, :on=> :collection
      end
     
      
    end  end # /api/v1/

  
  resources :temp_images
  resources :temp_users
  resources :credit_card_informations
  resources :user_payments do
    get :change_subscription, :on=> :collection
    post :save_subscription_change, :on=> :collection
    get :renew_subscription, :on=> :collection
    post :save_renew_subscription, :on=> :collection
  end
  
  resources :subscription_details do
    get :renew_subscription, :as => :renew
  end

  resources :deals_wizards do
    get :compaign_objectives, :on => :collection, :as => :objectives
    get :set_deal_wizard, :on => :collection, :as=> :set
    get :send_data, :on => :collection
  end

  resources :target_rules do
    post :show_params, :on => :collection

  end
  match '/set_params'=> 'target_rules#parameter_setup'
  resources :campaigns

  resources :deals do
    get :compaign_params, :on=> :collection
    post :upload_img, :on=> :collection
    get :set_preview, :on=> :collection
  end
  match 'save' => 'deals#save'
  resources :actions
  match "/users/actions" => "users#actions"
  get 'selectretailer', :to=>'users#select_retailer'

  devise_for :users , :controllers => {:registrations => "users"}    #Modified for Retailor

  devise_scope :user do
    resources :users  , :only => [:upload_pic, :index,:show,:new,:create, :edit,:update,:destroy,:switch,:switchbacktoadmin,:actions]    #Modified for Retailor
    get 'sign_in', :to=>'devise/sessions#new'
    delete 'sign_out', :to=>'devise/sessions#destroy'

    get 'switch', :to=>'users#switch'  #Modified for Retailor
    get 'switchbacktoadmin', :to=>'users#switchbacktoadmin'  #Modified for Retailor
    
  end
  root :to => "home#actions"

  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  before_filter :authenticate_user!
  
  def actions
    #to display main screen of actions
  end
end

app/views/home/shared/_adminlinks.erb

  <%= link_to 'Add a New Zone?', new_admin_zone_path , :style=>"width:300px;" , :class=>"edgyBlueButton" %>
  <br><br>
  <%= link_to 'Add a New Retailer?', new_user_path , :style=>"width:300px;" , :class=>"edgyBlueButton" %>
  <br><br>
   <%= link_to 'Access Retailer Accounts?', switch_path , :style=>"width:300px;" , :class=>"edgyBlueButton" %>
  <br><br>
  <%= link_to 'Add a Classified Ad?', new_admin_classified_path , :style=>"width:300px;" , :class=>"edgyBlueButton" %>
  <br><br>
  <%= link_to 'Add a Question of the Day?', new_admin_question_path , :style=>"width:300px;" , :class=>"edgyBlueButton" %>
  <br><br>
  <a class="edgyBlueButton" href="#" style="width:300px;">View Statistics?</a>
  <br><br>

app/views/home/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/home/shared/_retailerlinks.erb
<a class="edgyBlueButton" href="#" style="width:300px;">Take a Tour?</a><br /><br />
<%= link_to 'Create New Coupon or Deal Campaign?', new_deal_path , :style=>"width:300px;" , :class=>"edgyBlueButton" %>
<br /><br />
<%if current_user.sign_in_count>1%>
    <%= link_to 'Track, Edit or Delete an Existing Campaign?', deals_path , :style=>"width:300px;" , :class=>"edgyBlueButton" %>
    <br /><br />
<%end%>
<%= link_to 'View or Edit your Account/Subscription Information?', user_url(:id => current_user.id) , :style=>"width:300px;" , :class=>"edgyBlueButton" %>
<br /><br />
<%= link_to 'Contact Us?', new_contactu_path , :style=>"width:300px;" , :class=>"edgyBlueButton" %>
<br /><br />
<%unless cookies[:remember_admin_id].nil? %>
    <%= link_to 'Back to Admin', switchbacktoadmin_path , :style=>"width:300px;" , :class=>"edgyBlueButton" %>
<% end %>
<br /><br />